Repository mycelium-com/wallet-android-spvmodule-bch, pull requests merged in 2018-04, with the labels that each got.

#44 only call spv service with known actions
  src/main/java/com/mycelium/spvmodule/SpvMessageReceiver.kt
Labels: maintenance

#50 only call spv service with known actions 2.0
  src/main/java/com/mycelium/spvmodule/SpvMessageReceiver.kt
Labels: maintenance

#59 #825 Auto-uninstall all MBW modules after MBW removal
  src/main/AndroidManifest.xml
  src/main/java/com/mycelium/spvmodule/PackageRemovedReceiver.kt
Labels: enhancement

#62 826 Caсhe BCH balance and update it only if a new value is received from the BCH module
  src/main/java/com/mycelium/spvmodule/providers/TransactionContentProvider.kt
Labels: bug
